CREATE TABLE IF NOT EXISTS `vct_assets` (
    `ID` INT NOT NULL AUTO_INCREMENT ,
    `path` VARCHAR(145) NOT NULL UNIQUE ,
    `mime_type` VARCHAR(85) ,
    `size` BIGINT , 
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB;
