<?php

namespace Vector\DataObject;

use Vector\Module\DataObject\AbstractObject;
use Vector\Module\DataObject\Attribute\Property;

if (!defined('NO_DIRECT_ACCESS')) {
    header('HTTP/1.1 403 Forbidden');
    die();
}

class User extends AbstractObject
{
    protected string $tablename = 'vct_users';
    protected string $primary = 'ID';
    
    /**
     * @var ?int $ID
     * User ID, autogenerated on creation.
     */
    #[Property(Column: 'ID')]
    protected ?int $ID = null;

    /**
     * @var string $email
     * User's email, required.
     */
    #[Property(Column: 'email')]
    protected string $email;

    /**
     * @var string $password
     * User's password.
     */
    #[Property(Column: 'password')]
    protected ?string $password = null;

    /**
     * @var ?string $username
     * User's username.
     */
    #[Property(Column: 'username')]
    protected ?string $username = null;

    /**
     * @var ?string $createdAt
     * User's creation date.
     */
    protected ?string $createdAt = null;

    /**
     * @var ?string $modifiedAt
     * User's modification date.
     */
    protected ?string $modifiedAt = null;

    /**
     * @var ?string $lastLogin
     * User's last login date or null.
     */
     #[Property(Column: 'last_login')]
    protected ?string $lastLogin = null;

    /**
     * @package Vector
     * Vector\DataObject\User->getId()
     * @return ?int
     */
    public function getId(): ?int
    {
        return $this->ID;
    }

    /**
     * @package Vector
     * Vector\DataObject\User->getEmail()
     * @return ?string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @package Vector
     * Vector\DataObject\User->setEmail()
     * @param string $email
     * @return void
     */
    public function setEmail(string $email): void
    {
        $this->email = trim($email);
    }

    /**
     * @package Vector
     * Vector\DataObject\User->getPassword()
     * @return ?string
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    /**
     * @package Vector
     * Vector\DataObject\User->setPassword()
     * @param string $password
     * @return void
     */
    public function setPassword(string $password): void
    {
        $this->password = hash('sha256', $password);
    }

    /**
     * @package Vector
     * Vector\DataObject\User->getUsername()
     * @return ?string
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * @package Vector
     * Vector\DataObject\User->setUsername()
     * @param string $email
     * @return void
     */
    public function setUsername(string $username): void
    {
        $this->username = trim($username);
    }

    /**
     * @package Vector
     * Vector\DataObject\User->getCreatedAt()
     * @return ?string
     */
    public function getCreatedAt(): ?string
    {
        return $this->createdAt;
    }

    /**
     * @package Vector
     * Vector\DataObject\User->getModifiedAt()
     * @return ?string
     */
    public function getModifiedAt(): ?string
    {
        return $this->modifiedAt;
    }

    /**
     * @package Vector
     * Vector\DataObject\User->getLastLogin()
     * @return ?string
     */
    public function getLastLogin(): ?string
    {
        return $this->lastLogin;
    }

    /**
     * @package Vector
     * Vector\DataObject\User->setLastLogin()
     * @param ?string $time
     * @return void
     */
    public function setLastLogin(?string $time): void
    {
        $this->lastLogin = $time;
    }
}
